"""add new dynamic columns

Revision ID: e79ddd9bcb1a
Revises: a49ad66aa0f1
Create Date: 2025-05-22 13:03:04.531407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79ddd9bcb1a'
down_revision = ''
branch_labels = None
depends_on = None


def upgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynamic_ia_c_challenge', sa.Column('additional', sa.JSON(), nullable=True))
    op.add_column('dynamic_ia_c_challenge', sa.Column('max', sa.Integer(), nullable=True))
    op.add_column('dynamic_ia_c_challenge', sa.Column('min', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dynamic_ia_c_challenge', 'min')
    op.drop_column('dynamic_ia_c_challenge', 'max')
    op.drop_column('dynamic_ia_c_challenge', 'additional')
    # ### end Alembic commands ###