services:
  ctfd:
    image: ctfd/ctfd:3.7.4@sha256:b2cc1ff1767d919282cf9811ec41a9a4f994d502f502b4a8852999ffb1b7e81a
    ports:
      - 8000:8000
    networks:
      - testing
    volumes:
      - ../:/opt/CTFd/CTFd/plugins/ctfd-chall-manager
    environment:
      LOG_LEVEL: DEBUG
      PLUGIN_SETTINGS_CM_API_URL: http://chall-manager:9090/api/v1
      PLUGIN_SETTINGS_CM_MANA_TOTAL: 15

  chall-manager:
    image: ctferio/chall-manager:dev
    ports:
      - 9090:9090
    environment:
      GATEWAY: true
    networks:
      - testing

networks:
  testing:
    driver: bridge
